sudo: false
language: node_js
node_js:
  - "13"
before_install:
  - npm install -g npm
before_script:
  - npm install -g grunt-cli
matrix:
  fast_finish: true
deploy:
  provider: pages
  local_dir: prod
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
